spin_manifest_version = 2

[application]
name = "code-pls"
version = "0.1.0"
authors = ["ro"]
description = "Simple bot to prompt coding questions"

[[trigger.http]]
route = "/backend/..."
component = "code-pls"

[component.code-pls]
source = "target/wasm32-wasi/release/code_pls.wasm"
ai_models = ["codellama-instruct"]
key_value_stores = ["default"]

[component.code-pls.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**", "Cargo.toml"]

[[trigger.http]]
route = "/..."
component = "bot-frontend"

[component.bot-frontend]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "assets", destination = "/" }]
